version: '3'
services:
  build-server:
    build: build-server/
    volumes:
      - ./shareddir:/shareddir

  run-server:
    image: tomcat:9.0.8-jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./shareddir:/usr/local/tomcat/webapps
    depends_on:
      - build-server





